### ISSUE TITLE
Drop EOL'ed JDK versions

### ISSUE THREAD

**Issue by sormuras** [junit-team/build-env#1]
Drop [JDK 12](https://jdk.java.net/12) and [JDK 13](https://jdk.java.net/13) -- they're both superseded.

**Comment by marcphilipp** [comment]
Some people might still use them, so I'd keep them for now.

**Comment by sormuras** [comment]
Done via https://github.com/junit-team/build-env/commit/ff4ab2654f4d9f9a7e66cdee7250cbfe7c16b800
